cmake: Add "-std=c99" flag only if PYTHON_VERSION >= 3.6
Flag was introduced in python/cpython@7490577. Following up commits includes:
* python/cpython@d170256 (put -std=c99 in CFLAGS_NODIST)
* python/cpython@7f9eb6e (Issue 28017: Use -std=gnu99 to get C99 with GNU
  extensions for bluetooth.h on big endian.)
* python/cpython@93b2dee (compile with -std=c99 instead of -std=gnu99;
  use kiddie-gloves with bluetooth/bluetooh.h (#28017))

Adding this flag when building Python 2.7.x causes errors like the
following:

/home/travis/python-cmake-buildsystem/python-cmake-buildsystem/Python-2.7.14/Modules/linuxaudiodev.c:62:17: error: ‘AFMT_MU_LAW’ undeclared here (not in a function)
{  8,       AFMT_MU_LAW, "logarithmic mu-law 8-bit audio" },
^
/home/travis/python-cmake-buildsystem/python-cmake-buildsystem/Python-2.7.14/Modules/linuxaudiodev.c:63:17: error: ‘AFMT_A_LAW’ undeclared here (not in a function)
{  8,       AFMT_A_LAW,  "logarithmic A-law 8-bit audio" },
^
[...]