_testconsole: Fix link error when attempting to build extension as builtin on Linux
This commit fixes a regression introduced in e0017a7 (3.6.x: Add support
for building _testconsole module) ensuring the module is excluded on platform
different from windows.

It fixes the following error when building with BUILD_EXTENSIONS_AS_BUILTIN
enabled on Linux:

  CMakeFiles/_freeze_importlib.dir/__/__/CMakeFiles/config.c.o:(.data+0x308): undefined reference to `PyInit__testconsole'