Fix failing tests on Windows by making more modules built-in
Some of Python's standard regression tests are failing on Windows. For example:

    $ ./bin/python -m test.regrtest -v test_codecs
    [...]
    ======================================================================
    ERROR: test_bad_decode_args (test.test_codecs.BasicUnicodeTest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "c:\dev\p\build\INSTALL\Lib\test\test_codecs.py", line 1693, in test_bad_decode_args
        decoder = codecs.getdecoder(encoding)
      File "c:\dev\p\build\INSTALL\Lib\codecs.py", line 949, in getdecoder
        return lookup(encoding).decode
    LookupError: unknown encoding: big5

The root cause is that some modules can't be loaded:

    >>> import _codecs_tw
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ImportError: dynamic module does not define init function (init_codecs_tw)

In the standard Windows Python build a number of modules are builtin. sys.builtin_module_names lists the builtin modules. This commit explicitly marks those modules as builtin on Windows.

For reference, Python from the pre-built 2.7.10 x86-64 installer shows:

Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> print sys.builtin_module_names
('__builtin__', '__main__', '_ast', '_bisect', '_codecs', '_codecs_cn', '_codecs_hk', '_codecs_iso2022', '_codecs_jp', '_codecs_kr', '_codecs_tw', '_collections', '_csv', '_functools', '_heapq', '_hotshot', '_io', '_json', '_locale', '_lsprof', '_md5', '_multibytecodec', '_random', '_sha', '_sha256', '_sha512', '_sre', '_struct', '_subprocess', '_symtable', '_warnings', '_weakref', '_winreg', 'array', 'audioop', 'binascii', 'cPickle', 'cStringIO', 'cmath', 'datetime', 'errno', 'exceptions', 'future_builtins', 'gc', 'imageop', 'imp', 'itertools', 'marshal', 'math', 'mmap', 'msvcrt', 'nt', 'operator', 'parser', 'signal', 'strop', 'sys', 'thread', 'time', 'xxsubtype', 'zipimport', 'zlib')