python3: Fix link error by improving generation of python3stub.def
This commit fixes regression originally introduced in b774ba7 (python3: Build
"python3dll" and fix msvc "xxlimited" link issue.)

The previous implementation of the "generate_libpythonstub_def" module
was omitting the last line of "python3.def". This was causing the following
link error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol _Py_VaBuildValue_SizeT	libpython3-shared	D:\T\python-cmake-buildsystem-build\CMakeBuild\libpython\python3.def	1