Fix building on windows
Following commit c6b4b6d (Fix undeclared PyDateTimeAPI error when building
_testcapi module as builtin), building on Windows gives the following
error in Python.sln/libpython-shared.vcxproj:

    1>C:\dev\p\build\python-prefix\src\python\Modules\timemodule.c(1062): error C2491: '_PyTime_FloatTime' : definition of dllimport function not allowed

This commit fixes the build by (1) partially reverting c6b4b6d ensuring
that Py_BUILD_CORE is defined for all files in libpython and
(2) always building _testcapi extension as a shared module.

Co-authored-by: Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>