3.8.x: Fix test_fcntl on macOS ensuring _posixshmem module is built
This commit addresses a regression introduced in 5cf5b7679 (Add support
for building Python 3.8.x) adding support for building extension _posixshmem
based of python/cpython@e5ef45b8f. It turns out module should be built on
both Unix (including macOS) and not only Linux.

It fixes error like the following reported when running 3.8.x or
3.9.x tests:

  ERROR: test_lockf_exclusive (test.test_fcntl.TestFcntl)

  Traceback (most recent call last):
    File "/Users/runner/work/python-cmake-buildsystem/python-cmake-buildsystem/build/lib/python3.8/test/test_fcntl.py", line 162, in test_lockf_exclusive
      p.start()
    File "/Users/runner/work/python-cmake-buildsystem/python-cmake-buildsystem/build/lib/python3.8/multiprocessing/process.py", line 121, in start
      self._popen = self._Popen(self)
    File "/Users/runner/work/python-cmake-buildsystem/python-cmake-buildsystem/build/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
      return _default_context.get_context().Process._Popen(process_obj)
    File "/Users/runner/work/python-cmake-buildsystem/python-cmake-buildsystem/build/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
      return Popen(process_obj)
    File "/Users/runner/work/python-cmake-buildsystem/python-cmake-buildsystem/build/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
      super().__init__(process_obj)
    File "/Users/runner/work/python-cmake-buildsystem/python-cmake-buildsystem/build/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
      self._launch(process_obj)
    File "/Users/runner/work/python-cmake-buildsystem/python-cmake-buildsystem/build/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 39, in _launch
      from . import resource_tracker
    File "/Users/runner/work/python-cmake-buildsystem/python-cmake-buildsystem/build/lib/python3.8/multiprocessing/resource_tracker.py", line 38, in <module>
      import _posixshmem
  ModuleNotFoundError: No module named '_posixshmem'