cmake: Fix undefined reference to gss_* symbols when WITH_STATIC_DEPENDENCIES is ON
Check if tirpc static library and its dependencies can be linked statically
and set TIRPC_LIBRARY_STATIC_DEPENDENCY_REQUIRED and TIRPC_STATIC_LIBRARIES.

If the tirpc static library is built with the gssapi feature, and no gssapi_krb5
static library can be found, the python extensions depending on tirpc should be
disabled

Indeed, minimal support for static linking in krb5 was only re-introduced starting
with krb5-1.19.2 (see [1]) which may not yet be available (see [2]).

[1] https://github.com/krb5/krb5/commit/af44e8dee9b5bfffb05eb5a9b89c79c02ab7c2ff
[2] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=439039

Fixes #227