circleci/linux: Update python 2.7.14 -> 2.7.15, 3.6.4 -> 3.6.7, remove 3.5.5
* Update from 2.7.14 to 2.7.15 fixes undefined reference to `makedev',
  `minor' and `major'.
   Starting with 2.7.15, commit python/cpython@ffa7011cb ([2.7] bpo-31343:
   Include sys/sysmacros.h (GH-3318) (GH-3345))

* Remove testing of 3.5.5. Python 3.5.x EOL (end of life) was 4 years ago.
  See https://endoflife.date/python