extensions: Generalize the built-in of Windows extensions to all compilers
This commit also fixes expat build error using MinGW:

/usr/Python-2.7.11/Modules/expat/xmlparse.c:83:2: error: #error memmove does not exist on this platform, nor is a substitute available
 #error memmove does not exist on this platform, nor is a substitute available
  ^