Fix building on Windows
Following commit c6b4b6d5f31449449a3798fab2640aeaf1d0d544, building on
Windows gives the following error in Python.sln/libpython-shared.vcxproj:

    1>C:\dev\p\build\python-prefix\src\python\Modules\timemodule.c(1062): error C2491: '_PyTime_FloatTime' : definition of dllimport function not allowed

Defining Py_BUILD_CORE for just timemodule.c fixes the compile error,
but then the following linker error occurs:

    1>LINK : fatal error LNK1104: cannot open file 'python27.lib'

This commit fixes the build by ensuring that Py_BUILD_CORE is defined
for all files in libpython-shared.vcxproj.